# Learning Spatial Relationships with MISTy on gut spatial data (stem cell niche 2)
**Developed by:** Anna Maguza  
**Affiliation:** Faculty of Medicine, Würzburg University  
**Creation date:** 9th April 2025  
**Last modified date:** 9th April 2025  

In this notebook, we:  
  
* Calculate pathway activities with decoupler  
* Run MISTy to understand how cell surrounding influence on cell behaviour  
* Analyze pathway, transcription factors and CCI influence

## Import packages

In [1]:
import scanpy as sc
import decoupler as dc
import plotnine as p9
import liana as li
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import anndata as ad

import json
from datetime import datetime
import squidpy as sq

/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/anndata/utils.py:429: FutureWarning: Importing read_csv from `anndata` is deprecated. Import anndata.io.read_csv instead.
  warnings.warn(msg, FutureWarning)
/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/anndata/utils.py:429: FutureWarning: Importing read_excel from `anndata` is deprecated. Import anndata.io.read_excel instead.
  warnings.warn(msg, FutureWarning)
/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/anndata/utils.py:429: FutureWarning: Importing read_hdf from `anndata` is deprecated. Import anndata.io.read_hdf instead.
  warnings.warn(msg, FutureWarning)
/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/anndata/utils.py:429: FutureWarning: Importing read_loom from `anndata` is deprecated. Import anndata.io.read_loom instead.
  warnings.warn(msg, FutureWarning)
/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/anndata/utils.py:429: FutureWarning: Importing read_mtx from `anndata` is deprecated. Import anndata.io.read_mtx instead.
  warnings.warn(msg, FutureWarning)
/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/anndata/utils.py:429: FutureWarning: Importing read_text from `anndata` is deprecated. Import anndata.io.read_text instead.
  warnings.warn(msg, FutureWarning)
/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/anndata/utils.py:429: FutureWarning: Importing read_umi_tools from `anndata` is deprecated. Import anndata.io.read_umi_tools instead.
  warnings.warn(msg, FutureWarning)
/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
OMP: Info #276: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/dask/dataframe/__init__.py:31: FutureWarning: The legacy Dask DataFrame implementation is deprecated and will be removed in a future version. Set the configuration option `dataframe.query-planning` to `True` or None to enable the new Dask Dataframe implementation and silence this warning.
/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/anndata/utils.py:429: FutureWarning: Importing read_text from `anndata` is deprecated. Import anndata.io.read_text instead.

In [2]:
from liana.method import MistyData, genericMistyData, lrMistyData
from liana.method.sp import RandomForestModel, LinearModel, RobustLinearModel

## Set up notebooks

In [3]:
timestamp = datetime.now().strftime('%d%m%Y_%H%M%S')

In [4]:
plt.rcParams['figure.dpi'] = 300
plt.rcParams['figure.figsize'] = (15, 15)

## Load imputed Xenium data

In [5]:
adata = sc.read_h5ad('data/gut_data/maxfuse_checkpoints/gut_hs_XeniumHealthyColon_maxfuse_imputed_and_originalcounts_updated_niches_09042025_131844_log.h5ad')

+ Leave only niche 2

In [6]:
adata = adata[adata.obs['latent_leiden_0.4'] == '2'].copy()

In [7]:
adata

AnnData object with n_obs × n_vars = 25249 × 10281
    obs: 'Study_name', 'Donor_ID', 'Library_Preparation_Protocol', 'dataset', '_scvi_batch', '_scvi_labels', 'seed_labels', 'C_scANVI', 'SC_subsets', 'Cell_State', 'cell_id', 'x_centroid', 'y_centroid', 'transcript_counts', 'control_probe_counts', 'control_codeword_counts', 'unassigned_codeword_counts', 'deprecated_codeword_counts', 'total_counts', 'cell_area', 'nucleus_area', 'n_counts', 'REG4_score', 'gdT', 'Endothelial cells', 'latent_leiden_0.4', 'CD24_ligand_receptor_target_gene_GP', 'SLPI_ligand_receptor_target_gene_GP', 'CXCL14_ligand_receptor_target_gene_GP', 'ANPEP_ligand_receptor_target_gene_GP', 'IL1B_ligand_receptor_target_gene_GP', 'TIMP3_ligand_receptor_target_gene_GP', 'CDH1_ligand_receptor_target_gene_GP', 'TNXB_ligand_receptor_target_gene_GP', 'CLU_ligand_receptor_target_gene_GP', 'TFF1_ligand_receptor_target_gene_GP', 'CCL11_ligand_receptor_target_gene_GP', 'ROBO1_ligand_receptor_target_gene_GP', 'NRG3_ligand_receptor_target_gene_GP', 'gamma-Aminobutyric acid_metabolite_enzyme_sensor_GP', 'Add-on_14_GP', 'THBS1_ligand_receptor_target_gene_GP', 'C1QA_ligand_receptor_target_gene_GP', 'BMP5_ligand_receptor_target_gene_GP', 'Vitamin A_metabolite_enzyme_sensor_GP', 'COL5A2_ligand_receptor_target_gene_GP', 'FCN1_ligand_receptor_target_gene_GP', 'Add-on_74_GP', 'Add-on_22_GP', 'CTSG_ligand_receptor_target_gene_GP', 'APOE_ligand_receptor_target_gene_GP', 'CD6_ligand_receptor_target_gene_GP', 'FCER2_ligand_receptor_target_gene_GP', 'NID1_ligand_receptor_target_gene_GP', 'IGFBP7_ligand_receptor_target_gene_GP', 'COL11A1_ligand_receptor_target_gene_GP', 'CCL20_ligand_receptor_target_gene_GP', 'COL1A1_ligand_receptor_target_gene_GP', 'Add-on_36_GP', 'CEACAM6_ligand_receptor_target_gene_GP', 'CXCL13_ligand_receptor_target_gene_GP', 'AZGP1_ligand_receptor_target_gene_GP', 'Add-on_73_GP', 'COL19A1_ligand_receptor_target_gene_GP', 'CXCL10_ligand_receptor_GP', 'CXCL2_ligand_receptor_target_gene_GP', 'INSL5_ligand_receptor_target_gene_GP', 'GUCA2B_ligand_receptor_target_gene_GP', 'CXCL1_ligand_receptor_target_gene_GP', 'Add-on_13_GP', 'Add-on_11_GP', 'CCL13_ligand_receptor_GP', 'Add-on_35_GP', 'Add-on_24_GP', 'Add-on_7_GP', 'Add-on_55_GP', 'GUCA2A_ligand_receptor_target_gene_GP', 'CXCL10_ligand_receptor_target_gene_GP', 'CCL5_ligand_receptor_target_gene_GP', 'Add-on_44_GP', 'Add-on_4_GP', 'CEACAM1_ligand_receptor_target_gene_GP', 'S100A12_ligand_receptor_target_gene_GP', 'MMP1_ligand_receptor_target_gene_GP', 'PAPLN_ligand_receptor_target_gene_GP', 'TNFSF13B_ligand_receptor_target_gene_GP', 'IFNG_ligand_receptor_target_gene_GP', 'CD79B_ligand_receptor_target_gene_GP', 'VWF_ligand_receptor_target_gene_GP', 'Add-on_56_GP', 'Add-on_78_GP', 'BMP4_ligand_receptor_target_gene_GP', 'TNC_ligand_receptor_target_gene_GP', 'CEACAM5_ligand_receptor_target_gene_GP', 'UCN3_ligand_receptor_target_gene_GP', 'Add-on_49_GP', 'HHLA2_ligand_receptor_target_gene_GP', 'CXCL3_ligand_receptor_target_gene_GP', 'IL32_ligand_receptor_target_gene_GP', 'Add-on_52_GP', 'CCL13_ligand_receptor_target_gene_GP', 'Add-on_50_GP', 'Add-on_26_GP', 'LEFTY1_ligand_receptor_target_gene_GP', 'Add-on_0_GP', 'CEACAM7_ligand_receptor_target_gene_GP', 'Add-on_45_GP', 'RSPO3_ligand_receptor_target_gene_GP', 'Add-on_62_GP', 'Add-on_27_GP', 'SLC6A8_ligand_receptor_target_gene_GP', 'Add-on_53_GP', 'TTR_ligand_receptor_target_gene_GP', 'Add-on_51_GP', 'Add-on_92_GP', 'XCL2_ligand_receptor_target_gene_GP', 'WNT5B_ligand_receptor_target_gene_GP', 'Add-on_39_GP', 'AREG_ligand_receptor_target_gene_GP', 'NRXN1_ligand_receptor_target_gene_GP', 'Add-on_1_GP', 'Add-on_12_GP', 'CD177_ligand_receptor_GP', 'NRG1_ligand_receptor_target_gene_GP', 'GREM1_ligand_receptor_target_gene_GP', 'Add-on_98_GP', 'INHBA_ligand_receptor_target_gene_GP', 'Add-on_88_GP', 'Add-on_10_GP', 'Add-on_79_GP', 'Add-on_9_GP', 'CCL4_ligand_receptor_target_gene_GP', 'Add-on_43_GP', 'SELL_ligand_receptor_target_gene_GP', 'Add-on_41_GP', 'HDC_ligand_receptor_target_gene_GP', 'Add-on_19_GP', 'RBP4_ligand_receptor_target_gene_GP', 'RARRES2_ligand_receptor_target_gene_GP', 'ANXA1_ligand_receptor_target_gene_GP', 'Add-on_6_GP', 'LAMA2_ligand_receptor_target_gene_GP', 'Add-on_16_GP', 'IL22_ligand_receptor_target_gene_GP', 'GZMB_ligand_receptor_target_gene_GP', 'Add-on_32_GP', 'COL17A1_ligand_receptor_target_gene_GP', 'Add-on_60_GP', 'CD7_ligand_receptor_target_gene_GP', 'Add-on_20_GP', 'Norepinephrine_metabolite_enzyme_sensor_GP', 'Add-on_21_GP', 'SFRP2_ligand_receptor_target_gene_GP', 'Add-on_65_GP', 'THBS2_ligand_receptor_target_gene_GP', 'Add-on_89_GP', 'LTB_ligand_receptor_target_gene_GP', 'SERPINE1_ligand_receptor_target_gene_GP', 'Add-on_87_GP', 'MFAP5_ligand_receptor_target_gene_GP', 'Add-on_70_GP', 'APOB_ligand_receptor_target_gene_GP', 'Add-on_81_GP', 'Add-on_61_GP', 'Add-on_91_GP', 'CD14_ligand_receptor_target_gene_GP', 'Add-on_80_GP', 'Add-on_29_GP', 'Add-on_77_GP', 'Add-on_84_GP', 'Add-on_25_GP', 'TIGIT_ligand_receptor_target_gene_GP', 'CADM2_ligand_receptor_target_gene_GP', 'NPNT_ligand_receptor_target_gene_GP', 'VCAN_ligand_receptor_target_gene_GP', 'CD40LG_ligand_receptor_target_gene_GP', 'EPCAM_ligand_receptor_target_gene_GP', 'Add-on_18_GP', 'LCN2_ligand_receptor_target_gene_GP', 'Add-on_67_GP', 'Add-on_97_GP', 'Add-on_37_GP', 'Add-on_90_GP', 'Add-on_46_GP', 'Add-on_82_GP', 'Add-on_2_GP', 'Add-on_3_GP', 'Add-on_93_GP', 'Add-on_33_GP', 'Add-on_85_GP', 'Add-on_28_GP', 'Add-on_8_GP', 'Add-on_63_GP', 'Add-on_17_GP', 'Add-on_47_GP', 'Add-on_58_GP', 'Add-on_23_GP', 'Add-on_48_GP', 'CD2_ligand_receptor_target_gene_GP', 'TPSG1_ligand_receptor_target_gene_GP', 'GCG_ligand_receptor_target_gene_GP', 'Add-on_95_GP', 'Add-on_94_GP', 'Add-on_64_GP', 'Add-on_76_GP', 'Add-on_71_GP', 'C1QB_ligand_receptor_target_gene_GP', 'Add-on_68_GP', 'Add-on_34_GP', 'ADAM28_ligand_receptor_target_gene_GP', 'Add-on_99_GP', 'Add-on_30_GP', 'has_match', 'match_score'
    var: 'genes_type', 'gene_ids', 'feature_types', 'genome'
    obsm: 'X_umap', 'spatial'
    layers: 'counts'

+ Delete cells where imputation didnt actually work

In [8]:
adata = adata[adata.obs['has_match'] == True].copy()

In [9]:
adata

AnnData object with n_obs × n_vars = 15621 × 10281
    obs: 'Study_name', 'Donor_ID', 'Library_Preparation_Protocol', 'dataset', '_scvi_batch', '_scvi_labels', 'seed_labels', 'C_scANVI', 'SC_subsets', 'Cell_State', 'cell_id', 'x_centroid', 'y_centroid', 'transcript_counts', 'control_probe_counts', 'control_codeword_counts', 'unassigned_codeword_counts', 'deprecated_codeword_counts', 'total_counts', 'cell_area', 'nucleus_area', 'n_counts', 'REG4_score', 'gdT', 'Endothelial cells', 'latent_leiden_0.4', 'CD24_ligand_receptor_target_gene_GP', 'SLPI_ligand_receptor_target_gene_GP', 'CXCL14_ligand_receptor_target_gene_GP', 'ANPEP_ligand_receptor_target_gene_GP', 'IL1B_ligand_receptor_target_gene_GP', 'TIMP3_ligand_receptor_target_gene_GP', 'CDH1_ligand_receptor_target_gene_GP', 'TNXB_ligand_receptor_target_gene_GP', 'CLU_ligand_receptor_target_gene_GP', 'TFF1_ligand_receptor_target_gene_GP', 'CCL11_ligand_receptor_target_gene_GP', 'ROBO1_ligand_receptor_target_gene_GP', 'NRG3_ligand_receptor_target_gene_GP', 'gamma-Aminobutyric acid_metabolite_enzyme_sensor_GP', 'Add-on_14_GP', 'THBS1_ligand_receptor_target_gene_GP', 'C1QA_ligand_receptor_target_gene_GP', 'BMP5_ligand_receptor_target_gene_GP', 'Vitamin A_metabolite_enzyme_sensor_GP', 'COL5A2_ligand_receptor_target_gene_GP', 'FCN1_ligand_receptor_target_gene_GP', 'Add-on_74_GP', 'Add-on_22_GP', 'CTSG_ligand_receptor_target_gene_GP', 'APOE_ligand_receptor_target_gene_GP', 'CD6_ligand_receptor_target_gene_GP', 'FCER2_ligand_receptor_target_gene_GP', 'NID1_ligand_receptor_target_gene_GP', 'IGFBP7_ligand_receptor_target_gene_GP', 'COL11A1_ligand_receptor_target_gene_GP', 'CCL20_ligand_receptor_target_gene_GP', 'COL1A1_ligand_receptor_target_gene_GP', 'Add-on_36_GP', 'CEACAM6_ligand_receptor_target_gene_GP', 'CXCL13_ligand_receptor_target_gene_GP', 'AZGP1_ligand_receptor_target_gene_GP', 'Add-on_73_GP', 'COL19A1_ligand_receptor_target_gene_GP', 'CXCL10_ligand_receptor_GP', 'CXCL2_ligand_receptor_target_gene_GP', 'INSL5_ligand_receptor_target_gene_GP', 'GUCA2B_ligand_receptor_target_gene_GP', 'CXCL1_ligand_receptor_target_gene_GP', 'Add-on_13_GP', 'Add-on_11_GP', 'CCL13_ligand_receptor_GP', 'Add-on_35_GP', 'Add-on_24_GP', 'Add-on_7_GP', 'Add-on_55_GP', 'GUCA2A_ligand_receptor_target_gene_GP', 'CXCL10_ligand_receptor_target_gene_GP', 'CCL5_ligand_receptor_target_gene_GP', 'Add-on_44_GP', 'Add-on_4_GP', 'CEACAM1_ligand_receptor_target_gene_GP', 'S100A12_ligand_receptor_target_gene_GP', 'MMP1_ligand_receptor_target_gene_GP', 'PAPLN_ligand_receptor_target_gene_GP', 'TNFSF13B_ligand_receptor_target_gene_GP', 'IFNG_ligand_receptor_target_gene_GP', 'CD79B_ligand_receptor_target_gene_GP', 'VWF_ligand_receptor_target_gene_GP', 'Add-on_56_GP', 'Add-on_78_GP', 'BMP4_ligand_receptor_target_gene_GP', 'TNC_ligand_receptor_target_gene_GP', 'CEACAM5_ligand_receptor_target_gene_GP', 'UCN3_ligand_receptor_target_gene_GP', 'Add-on_49_GP', 'HHLA2_ligand_receptor_target_gene_GP', 'CXCL3_ligand_receptor_target_gene_GP', 'IL32_ligand_receptor_target_gene_GP', 'Add-on_52_GP', 'CCL13_ligand_receptor_target_gene_GP', 'Add-on_50_GP', 'Add-on_26_GP', 'LEFTY1_ligand_receptor_target_gene_GP', 'Add-on_0_GP', 'CEACAM7_ligand_receptor_target_gene_GP', 'Add-on_45_GP', 'RSPO3_ligand_receptor_target_gene_GP', 'Add-on_62_GP', 'Add-on_27_GP', 'SLC6A8_ligand_receptor_target_gene_GP', 'Add-on_53_GP', 'TTR_ligand_receptor_target_gene_GP', 'Add-on_51_GP', 'Add-on_92_GP', 'XCL2_ligand_receptor_target_gene_GP', 'WNT5B_ligand_receptor_target_gene_GP', 'Add-on_39_GP', 'AREG_ligand_receptor_target_gene_GP', 'NRXN1_ligand_receptor_target_gene_GP', 'Add-on_1_GP', 'Add-on_12_GP', 'CD177_ligand_receptor_GP', 'NRG1_ligand_receptor_target_gene_GP', 'GREM1_ligand_receptor_target_gene_GP', 'Add-on_98_GP', 'INHBA_ligand_receptor_target_gene_GP', 'Add-on_88_GP', 'Add-on_10_GP', 'Add-on_79_GP', 'Add-on_9_GP', 'CCL4_ligand_receptor_target_gene_GP', 'Add-on_43_GP', 'SELL_ligand_receptor_target_gene_GP', 'Add-on_41_GP', 'HDC_ligand_receptor_target_gene_GP', 'Add-on_19_GP', 'RBP4_ligand_receptor_target_gene_GP', 'RARRES2_ligand_receptor_target_gene_GP', 'ANXA1_ligand_receptor_target_gene_GP', 'Add-on_6_GP', 'LAMA2_ligand_receptor_target_gene_GP', 'Add-on_16_GP', 'IL22_ligand_receptor_target_gene_GP', 'GZMB_ligand_receptor_target_gene_GP', 'Add-on_32_GP', 'COL17A1_ligand_receptor_target_gene_GP', 'Add-on_60_GP', 'CD7_ligand_receptor_target_gene_GP', 'Add-on_20_GP', 'Norepinephrine_metabolite_enzyme_sensor_GP', 'Add-on_21_GP', 'SFRP2_ligand_receptor_target_gene_GP', 'Add-on_65_GP', 'THBS2_ligand_receptor_target_gene_GP', 'Add-on_89_GP', 'LTB_ligand_receptor_target_gene_GP', 'SERPINE1_ligand_receptor_target_gene_GP', 'Add-on_87_GP', 'MFAP5_ligand_receptor_target_gene_GP', 'Add-on_70_GP', 'APOB_ligand_receptor_target_gene_GP', 'Add-on_81_GP', 'Add-on_61_GP', 'Add-on_91_GP', 'CD14_ligand_receptor_target_gene_GP', 'Add-on_80_GP', 'Add-on_29_GP', 'Add-on_77_GP', 'Add-on_84_GP', 'Add-on_25_GP', 'TIGIT_ligand_receptor_target_gene_GP', 'CADM2_ligand_receptor_target_gene_GP', 'NPNT_ligand_receptor_target_gene_GP', 'VCAN_ligand_receptor_target_gene_GP', 'CD40LG_ligand_receptor_target_gene_GP', 'EPCAM_ligand_receptor_target_gene_GP', 'Add-on_18_GP', 'LCN2_ligand_receptor_target_gene_GP', 'Add-on_67_GP', 'Add-on_97_GP', 'Add-on_37_GP', 'Add-on_90_GP', 'Add-on_46_GP', 'Add-on_82_GP', 'Add-on_2_GP', 'Add-on_3_GP', 'Add-on_93_GP', 'Add-on_33_GP', 'Add-on_85_GP', 'Add-on_28_GP', 'Add-on_8_GP', 'Add-on_63_GP', 'Add-on_17_GP', 'Add-on_47_GP', 'Add-on_58_GP', 'Add-on_23_GP', 'Add-on_48_GP', 'CD2_ligand_receptor_target_gene_GP', 'TPSG1_ligand_receptor_target_gene_GP', 'GCG_ligand_receptor_target_gene_GP', 'Add-on_95_GP', 'Add-on_94_GP', 'Add-on_64_GP', 'Add-on_76_GP', 'Add-on_71_GP', 'C1QB_ligand_receptor_target_gene_GP', 'Add-on_68_GP', 'Add-on_34_GP', 'ADAM28_ligand_receptor_target_gene_GP', 'Add-on_99_GP', 'Add-on_30_GP', 'has_match', 'match_score'
    var: 'genes_type', 'gene_ids', 'feature_types', 'genome'
    obsm: 'X_umap', 'spatial'
    layers: 'counts'

+ Visualize the dataset with filtered niche

In [ ]:
plt.rcParams['figure.dpi'] = 300
plt.rcParams['figure.figsize'] = (7, 7)

# Your plotting code
sq.pl.spatial_scatter(
    adata,
    library_id="spatial",
    shape=None, 
    color=['C_scANVI', 'match_score'],
    size=1,
    frameon=False,
    alpha=1.0,
    cmap = 'magma_r',
    ncols=1,
    #crop_coord=[(6300, 1950, 7600, 2950)]

)
plt.savefig(f"figures/niche2_xenium_after_imputation.png", bbox_inches="tight", dpi=300)

## Funconomics

In [11]:
progeny = dc.get_progeny(organism='human', top=500)

Downloading data from `https://omnipathdb.org/queries/enzsub?format=json`
Downloading data from `https://omnipathdb.org/queries/interactions?format=json`
Downloading data from `https://omnipathdb.org/queries/complexes?format=json`
Downloading data from `https://omnipathdb.org/queries/annotations?format=json`
Downloading data from `https://omnipathdb.org/queries/intercell?format=json`
Downloading data from `https://omnipathdb.org/about?format=text`
Downloading annotations for all proteins from the following resources: `['PROGENy']`

In [12]:
dc.run_mlm(
    mat=adata,
    net=progeny,
    source='source',
    target='target',
    weight='weight',
    verbose=True,
    use_raw=False,
)

183 features of mat are empty, they will be removed.
Running mlm on mat with 15621 samples and 10098 targets for 14 sources.

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.45s/it]

In [13]:
acts_progeny = li.ut.obsm_to_adata(adata, 'mlm_estimate')

In [14]:
acts_progeny.var

Empty DataFrame
Columns: []
Index: [Androgen, EGFR, Estrogen, Hypoxia, JAK-STAT, MAPK, NFkB, PI3K, TGFb, TNFa, Trail, VEGF, WNT, p53]

In [ ]:
plt.rcParams['figure.dpi'] = 300
plt.rcParams['figure.figsize'] = (7, 7)

# Your plotting code
sq.pl.spatial_scatter(
    acts_progeny,
    library_id="spatial",
    shape=None, 
    color=['JAK-STAT', 'Androgen','Hypoxia', 'MAPK', 'EGFR', 'Estrogen'],
    size=1,
    frameon=False,
    alpha=1.0,
    cmap = 'RdBu_r',
    ncols=3,
    #crop_coord=[(6300, 1950, 7600, 2950)]

)
plt.savefig(f"figures/niche2_pathways_activity_in_spatial1.png", bbox_inches="tight", dpi=300)

In [ ]:
plt.rcParams['figure.dpi'] = 300
plt.rcParams['figure.figsize'] = (7, 7)

# Your plotting code
sq.pl.spatial_scatter(
    acts_progeny,
    library_id="spatial",
    shape=None, 
    color=['TGFb', 'TNFa', 'Trail', 'NFkB', 'PI3K', 'WNT', 'VEGF', 'p53'],
    size=1,
    frameon=False,
    alpha=1.0,
    cmap = 'RdBu_r',
    ncols=4,
    #crop_coord=[(6300, 1950, 7600, 2950)]

)
plt.savefig(f"figures/niche2_pathways_activity_in_spatial2.png", bbox_inches="tight", dpi=300)

## Formatting & Running MISTy

In [15]:
cell_types = adata.obs['C_scANVI'].unique()
print(f"Found {len(cell_types)} cell types: {cell_types}")

Found 24 cell types: ['Mast cells', 'Endothelial cells', 'Goblet cells', 'Tuft cells', 'EECs', ..., 'DC', 'Colonocyte', 'NK', 'Monocytes', 'BEST4+ epithelial']
Length: 24
Categories (24, object): ['B cells', 'BEST4+ epithelial', 'CD4 T', 'CD8 T', ..., 'Plasma cells', 'Stem cells', 'TA', 'Tuft cells']

In [16]:
compositions = pd.DataFrame(index=adata.obs_names, columns=cell_types)

In [17]:
compositions = compositions.fillna(0)

/var/folders/kr/nd4y_1_s34n42lrht8wdh4cr0000gq/T/ipykernel_40151/2262236102.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

In [18]:
for cell_type in cell_types:
    mask = adata.obs['C_scANVI'] == cell_type
    compositions.loc[mask, cell_type] = 1

In [19]:
adata.obsm['compositions'] = compositions

In [20]:
comps = ad.AnnData(
    X=adata.obsm['compositions'].values,
    obs=adata.obs,
    var=pd.DataFrame(index=adata.obsm['compositions'].columns),
    obsm=adata.obsm,
)

In [21]:
misty = genericMistyData(intra=comps, extra=acts_progeny, cutoff=0.05, bandwidth=200, n_neighs=6)

/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/anndata/_core/anndata.py:401: FutureWarning: The dtype argument is deprecated and will be removed in late 2024.
/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/anndata/_core/anndata.py:401: FutureWarning: The dtype argument is deprecated and will be removed in late 2024.
/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/anndata/_core/anndata.py:401: FutureWarning: The dtype argument is deprecated and will be removed in late 2024.
/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/mudata/_core/mudata.py:1531: FutureWarning: From 0.4 .update() will not pull obs/var columns from individual modalities by default anymore. Set mudata.set_options(pull_on_update=False) to adopt the new behaviour, which will become the default. Use new pull_obs/pull_var and push_obs/push_var methods for more flexibility.
/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/mudata/_core/mudata.py:931: UserWarning: Cannot join columns with the same name because var_names are intersecting.
/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/mudata/_core/mudata.py:1429: FutureWarning: From 0.4 .update() will not pull obs/var columns from individual modalities by default anymore. Set mudata.set_options(pull_on_update=False) to adopt the new behaviour, which will become the default. Use new pull_obs/pull_var and push_obs/push_var methods for more flexibility.
/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/liana/method/sp/_misty/_Misty.py:80: ImplicitModificationWarning: Setting element `.layers['weighted']` of view, initializing view as actual.
/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/liana/method/sp/_misty/_Misty.py:80: ImplicitModificationWarning: Setting element `.layers['weighted']` of view, initializing view as actual.

## Learn Relationships with MISTy

In [22]:
# Run this if you have time and resources
misty(model=RandomForestModel, n_jobs=-1, verbose = True, seed=1337)

Now learning: Stem cells: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:23<00:00,  7.75s/it]

In [ ]:
# Run this if you want it much faster and bit more simplistic 
#misty(model=LinearModel, k_cv=10, seed=1337, bypass_intra=True, verbose = True)

In [23]:
misty.uns['target_metrics'].head()

         target  intra_R2  multi_R2   gain_R2     intra     juxta      para
0  Goblet cells  0.145044  0.187104  0.042060  0.574741  0.283227  0.142031
1    Tuft cells  0.127314  0.165065  0.037751  0.571260  0.220752  0.207988
2    Stem cells  0.196757  0.308863  0.112106  0.479993  0.335247  0.184760

In [24]:
fig = (li.pl.target_metrics(misty, stat='intra_R2', return_fig=True))
print(fig)
fig.save("figures/niche2_misty_intra_R2.png", dpi=300)

/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/plotnine/ggplot.py:615: PlotnineWarning: Saving 5 x 5 in image.
/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/plotnine/ggplot.py:616: PlotnineWarning: Filename: /Users/annamaguza/Desktop/Repos/Fetal_stem_cells_analysis/6_cci_on_imputed_spatial/figures/niche2_misty_intra_R2.png

<ggplot: (500 x 500)>

In [25]:
fig = (li.pl.target_metrics(misty, stat='gain_R2'))
print(fig)
fig.save("figures/niche2_misty_gain_R2.png", dpi=300)

<ggplot: (500 x 500)>

/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/plotnine/ggplot.py:615: PlotnineWarning: Saving 5 x 5 in image.
/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/plotnine/ggplot.py:616: PlotnineWarning: Filename: /Users/annamaguza/Desktop/Repos/Fetal_stem_cells_analysis/6_cci_on_imputed_spatial/figures/niche2_misty_gain_R2.png

In [26]:
fig = (li.pl.contributions(misty, return_fig=True))
print(fig)
fig.save("figures/niche2_misty_contributions.png", dpi=300)

<ggplot: (500 x 500)>

/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/plotnine/ggplot.py:615: PlotnineWarning: Saving 5 x 5 in image.
/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/plotnine/ggplot.py:616: PlotnineWarning: Filename: /Users/annamaguza/Desktop/Repos/Fetal_stem_cells_analysis/6_cci_on_imputed_spatial/figures/niche2_misty_contributions.png

In [27]:
misty.uns['interactions'].head()

          target     predictor   view  importances
0   Goblet cells    Tuft cells  intra     0.349089
1   Goblet cells    Stem cells  intra     0.650911
16    Tuft cells  Goblet cells  intra     0.407265
17    Tuft cells    Stem cells  intra     0.592735
32    Stem cells  Goblet cells  intra     0.483182

In [28]:
fig = ((
    li.pl.interactions(misty, view='juxta', return_fig=True, figure_size=(7,5)) +
    p9.scale_fill_gradient2(low = "blue", mid = "white", high = "red", midpoint = 0)
))
print(fig)
fig.save("figures/niche2_misty_pathway_importance.png", dpi=300)

<ggplot: (700 x 500)>

/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/plotnine/ggplot.py:615: PlotnineWarning: Saving 7 x 5 in image.
/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/plotnine/ggplot.py:616: PlotnineWarning: Filename: /Users/annamaguza/Desktop/Repos/Fetal_stem_cells_analysis/6_cci_on_imputed_spatial/figures/niche2_misty_pathway_importance.png

## Estimate Transcription Factor activities with decoupler

In [29]:
net = dc.get_collectri()

In [30]:
dc.run_ulm(
    mat=adata,
    net=net,
    verbose=True,
    use_raw=False,
)

183 features of mat are empty, they will be removed.
Running ulm on mat with 15621 samples and 10098 targets for 590 sources.

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.16it/s]

In [31]:
acts_tfs = li.ut.obsm_to_adata(adata, 'ulm_estimate')

In [32]:
acts_tfs.var

Empty DataFrame
Columns: []
Index: [AEBP1, AHR, AIP, AIRE, AP1, APEX1, AR, ARID5B, ARNT, ARX, ASCL1, ASCL2, ATF1, ATF2, ATF3, ATF4, ATF5, ATF6, ATF7, ATOH1, ATOH7, BACH1, BACH2, BARX1, BARX2, BATF, BCL11A, BCL11B, BCL3, BCL6, BHLHA15, BHLHE40, BHLHE41, BMAL1, BMAL2, BRCA1, BRD4, CDX1, CDX2, CEBPA, CEBPB, CEBPD, CEBPE, CEBPG, CEBPZ, CIITA, CLOCK, CREB1, CREB3, CREB3L1, CREB5, CREBBP, CREBZF, CREM, CRX, CTBP1, CTBP2, CTCF, CTNNB1, CUX1, CXXC1, DACH1, DBP, DDIT3, DLX1, DLX2, DLX3, DLX4, DLX5, DMTF1, DNMT1, DNMT3A, DNMT3B, E2F1, E2F2, E2F3, E2F4, E2F6, EBF1, EBF3, EGR1, EGR2, EGR3, EGR4, EHF, ELF1, ELF2, ELF3, ELF4, ELF5, ELK1, ELK3, EMX2, EN1, ENO1, EOMES, EP300, EPAS1, ERF, ERG, ...]

[590 rows x 0 columns]

In [33]:
li.ut.spatial_neighbors(acts_tfs, cutoff=0.1, bandwidth=200, set_diag=True)

In [34]:
fig = (li.pl.connectivity(acts_tfs, idx=0, figure_size=(10,10)))
print(fig)
fig.save("figures/niche2_misty_liana_connectivity.png", dpi=300)

<ggplot: (1000 x 1000)>

/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/plotnine/ggplot.py:615: PlotnineWarning: Saving 10 x 10 in image.
/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/plotnine/ggplot.py:616: PlotnineWarning: Filename: /Users/annamaguza/Desktop/Repos/Fetal_stem_cells_analysis/6_cci_on_imputed_spatial/figures/niche2_misty_liana_connectivity.png

In [35]:
acts_progeny.obsm['spatial'] = acts_tfs.obsm['spatial']
acts_progeny.obsp['spatial_connectivities'] = acts_tfs.obsp['spatial_connectivities']

In [36]:
misty = MistyData(data={"intra": comps, "TFs": acts_tfs, "Pathways": acts_progeny})

/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/mudata/_core/mudata.py:1531: FutureWarning: From 0.4 .update() will not pull obs/var columns from individual modalities by default anymore. Set mudata.set_options(pull_on_update=False) to adopt the new behaviour, which will become the default. Use new pull_obs/pull_var and push_obs/push_var methods for more flexibility.
/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/mudata/_core/mudata.py:1429: FutureWarning: From 0.4 .update() will not pull obs/var columns from individual modalities by default anymore. Set mudata.set_options(pull_on_update=False) to adopt the new behaviour, which will become the default. Use new pull_obs/pull_var and push_obs/push_var methods for more flexibility.

In [37]:
misty(model=LinearModel, verbose=True, bypass_intra=True)

Now learning: BEST4+ epithelial:  96%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊            | 23/24 [01:00<00:02,  2.26s/it]/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/liana/method/sp/_misty/_Misty.py:318: RuntimeWarning: invalid value encountered in divide
Now learning: BEST4+ epithelial: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 24/24 [01:02<00:00,  2.62s/it]

In [38]:
fig = (li.pl.target_metrics(misty, stat='gain_R2'))
print(fig)
fig.save("figures/niche2_misty_TF-and_pathway_gain_R2.png", dpi=300)

/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/plotnine/ggplot.py:615: PlotnineWarning: Saving 5 x 5 in image.
/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/plotnine/ggplot.py:616: PlotnineWarning: Filename: /Users/annamaguza/Desktop/Repos/Fetal_stem_cells_analysis/6_cci_on_imputed_spatial/figures/niche2_misty_TF-and_pathway_gain_R2.png

<ggplot: (500 x 500)>

In [39]:
fig = (li.pl.contributions(misty, return_fig=True))
print(fig)
fig.save("figures/niche2_misty_contributions_TFs_and_pathways.png", dpi=300)

<ggplot: (500 x 500)>

/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/plotnine/ggplot.py:615: PlotnineWarning: Saving 5 x 5 in image.
/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/plotnine/ggplot.py:616: PlotnineWarning: Filename: /Users/annamaguza/Desktop/Repos/Fetal_stem_cells_analysis/6_cci_on_imputed_spatial/figures/niche2_misty_contributions_TFs_and_pathways.png
/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/plotnine/layer.py:344: PlotnineWarning: position_stack : Removed 2 rows containing missing values.

In [40]:
fig = (
li.pl.interactions(misty, view='TFs', top_n=20) +
    p9.labs(x='Transcription Factor', y='Cell type') +
    p9.theme_bw(base_size=14) +
    p9.theme(axis_text_x=p9.element_text(rotation=90, size=13)) +
    # change to blue-red
    p9.scale_fill_gradient2(low='blue', mid='white', high='red')
)

# Display the figure
print(fig)

# Save the figure to a file
fig.save("figures/niche2_misty_TFs.png", dpi=300)

<ggplot: (640 x 480)>

/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/plotnine/ggplot.py:615: PlotnineWarning: Saving 6.4 x 4.8 in image.
/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/plotnine/ggplot.py:616: PlotnineWarning: Filename: /Users/annamaguza/Desktop/Repos/Fetal_stem_cells_analysis/6_cci_on_imputed_spatial/figures/niche2_misty_TFs.png

## Ligand-Receptor Misty

In [41]:
misty = lrMistyData(adata, bandwidth=200, set_diag=False, cutoff=0.01, nz_threshold=0.1)

/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/anndata/_core/anndata.py:401: FutureWarning: The dtype argument is deprecated and will be removed in late 2024.
/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/anndata/_core/anndata.py:401: FutureWarning: The dtype argument is deprecated and will be removed in late 2024.
/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/anndata/_core/anndata.py:401: FutureWarning: The dtype argument is deprecated and will be removed in late 2024.
/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/mudata/_core/mudata.py:1531: FutureWarning: From 0.4 .update() will not pull obs/var columns from individual modalities by default anymore. Set mudata.set_options(pull_on_update=False) to adopt the new behaviour, which will become the default. Use new pull_obs/pull_var and push_obs/push_var methods for more flexibility.
/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/mudata/_core/mudata.py:931: UserWarning: Cannot join columns with the same name because var_names are intersecting.
/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/mudata/_core/mudata.py:1429: FutureWarning: From 0.4 .update() will not pull obs/var columns from individual modalities by default anymore. Set mudata.set_options(pull_on_update=False) to adopt the new behaviour, which will become the default. Use new pull_obs/pull_var and push_obs/push_var methods for more flexibility.
/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/liana/method/sp/_misty/_Misty.py:80: ImplicitModificationWarning: Setting element `.layers['weighted']` of view, initializing view as actual.

In [42]:
misty(bypass_intra=True, model=LinearModel, verbose=True)

Now learning: CR2:  11%|██████████████████████████████████                                                                                                                                                                                                                                                                                 | 46/415 [01:43<13:38,  2.22s/it]/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/liana/method/sp/_misty/_Misty.py:318: RuntimeWarning: invalid value encountered in divide
Now learning: TLR6:  13%|███████████████████████████████████████                                                                                                                                                                                                                                                                           | 53/415 [01:56<10:52,  1.80s/it]/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/liana/method/sp/_misty/_Misty.py:318: RuntimeWarning: invalid value encountered in divide
Now learning: CD244:  13%|████████████████████████████████████████▍                                                                                                                                                                                                                                                                        | 55/415 [02:00<10:45,  1.79s/it]/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/liana/method/sp/_misty/_Misty.py:318: RuntimeWarning: invalid value encountered in divide
Now learning: KIR2DL2:  14%|█████████████████████████████████████████▌                                                                                                                                                                                                                                                                     | 57/415 [02:04<11:19,  1.90s/it]/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/liana/method/sp/_misty/_Misty.py:318: RuntimeWarning: invalid value encountered in divide
Now learning: EPHB6:  19%|████████████████████████████████████████████████████████▌                                                                                                                                                                                                                                                        | 77/415 [02:42<10:50,  1.92s/it]/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/liana/method/sp/_misty/_Misty.py:318: RuntimeWarning: invalid value encountered in divide
Now learning: FLT3:  20%|█████████████████████████████████████████████████████████████▉                                                                                                                                                                                                                                                    | 84/415 [02:55<09:48,  1.78s/it]/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/liana/method/sp/_misty/_Misty.py:318: RuntimeWarning: invalid value encountered in divide
Now learning: ERBB4:  21%|████████████████████████████████████████████████████████████████▋                                                                                                                                                                                                                                                | 88/415 [03:02<09:50,  1.80s/it]/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/liana/method/sp/_misty/_Misty.py:318: RuntimeWarning: invalid value encountered in divide
Now learning: ITGA2B:  24%|███████████████████████████████████████████████████████████████████████▊                                                                                                                                                                                                                                        | 98/415 [03:21<10:06,  1.91s/it]/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/liana/method/sp/_misty/_Misty.py:318: RuntimeWarning: invalid value encountered in divide
Now learning: CD7:  26%|██████████████████████████████████████████████████████████████████████████████▉                                                                                                                                                                                                                                   | 107/415 [03:41<10:59,  2.14s/it]/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/liana/method/sp/_misty/_Misty.py:318: RuntimeWarning: invalid value encountered in divide
Now learning: IL27RA_IL6ST:  32%|███████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                                                                                                                         | 133/415 [04:39<09:29,  2.02s/it]/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/liana/method/sp/_misty/_Misty.py:318: RuntimeWarning: invalid value encountered in divide
Now learning: CCR3:  33%|███████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                                                                                                                             | 135/415 [04:42<09:01,  1.94s/it]/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/liana/method/sp/_misty/_Misty.py:318: RuntimeWarning: invalid value encountered in divide
Now learning: SSTR5:  33%|███████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                                                                                                                            | 136/415 [04:45<09:25,  2.03s/it]Variance of 'SSTR5' is 0.0, metrics set to NaN
Now learning: CCR8:  35%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                                                                                                                     | 146/415 [05:06<09:29,  2.12s/it]/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/liana/method/sp/_misty/_Misty.py:318: RuntimeWarning: invalid value encountered in divide
Now learning: PTCH1_SMO:  36%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                                                                                                                 | 148/415 [05:11<10:17,  2.31s/it]/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/liana/method/sp/_misty/_Misty.py:318: RuntimeWarning: invalid value encountered in divide
Now learning: TREM1:  37%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                                                                                                               | 154/415 [05:24<09:48,  2.25s/it]/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/liana/method/sp/_misty/_Misty.py:318: RuntimeWarning: invalid value encountered in divide
Now learning: KREMEN2:  38%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                                                                                                           | 157/415 [05:30<08:44,  2.03s/it]/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/liana/method/sp/_misty/_Misty.py:318: RuntimeWarning: invalid value encountered in divide
Now learning: ASGR2:  40%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                                                                                                       | 164/415 [05:44<08:49,  2.11s/it]/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/liana/method/sp/_misty/_Misty.py:318: RuntimeWarning: invalid value encountered in divide
Now learning: TGFBR1_TGFBR2:  41%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                                                                                             | 172/415 [06:03<08:55,  2.20s/it]/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/liana/method/sp/_misty/_Misty.py:318: RuntimeWarning: invalid value encountered in divide
Now learning: NPR3:  42%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                                                                                                | 175/415 [06:10<09:40,  2.42s/it]/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/liana/method/sp/_misty/_Misty.py:318: RuntimeWarning: invalid value encountered in divide
Now learning: GPR84:  44%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                                                                                          | 183/415 [06:27<08:19,  2.15s/it]/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/liana/method/sp/_misty/_Misty.py:318: RuntimeWarning: invalid value encountered in divide
Now learning: OPRL1:  44%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                                                                                         | 184/415 [06:29<08:01,  2.09s/it]/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/liana/method/sp/_misty/_Misty.py:318: RuntimeWarning: invalid value encountered in divide
Now learning: GCGR:  45%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                                                                                       | 187/415 [06:34<07:22,  1.94s/it]/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/liana/method/sp/_misty/_Misty.py:318: RuntimeWarning: invalid value encountered in divide
Now learning: NPY2R:  46%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                                                                                    | 191/415 [06:42<06:57,  1.86s/it]Variance of 'NPY2R' is 0.0, metrics set to NaN
Now learning: GPR83:  46%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                                                                                   | 192/415 [06:44<07:26,  2.00s/it]/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/liana/method/sp/_misty/_Misty.py:318: RuntimeWarning: invalid value encountered in divide
Now learning: CXCR1:  48%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                                                                             | 200/415 [06:59<07:10,  2.00s/it]/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/liana/method/sp/_misty/_Misty.py:318: RuntimeWarning: invalid value encountered in divide
Now learning: RXFP1:  49%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                                                                            | 202/415 [07:04<07:52,  2.22s/it]/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/liana/method/sp/_misty/_Misty.py:318: RuntimeWarning: invalid value encountered in divide
Now learning: IL13RA1_IL4R:  51%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                                                                                                  | 210/415 [07:22<07:57,  2.33s/it]/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/liana/method/sp/_misty/_Misty.py:318: RuntimeWarning: invalid value encountered in divide
Now learning: IL6R_IL6ST:  51%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                                                                 | 213/415 [07:29<07:47,  2.31s/it]/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/liana/method/sp/_misty/_Misty.py:318: RuntimeWarning: invalid value encountered in divide
Now learning: CRHR1:  52%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                                                                  | 215/415 [07:33<07:18,  2.19s/it]/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/liana/method/sp/_misty/_Misty.py:318: RuntimeWarning: invalid value encountered in divide
Now learning: BRS3:  53%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                                                              | 221/415 [07:46<06:41,  2.07s/it]Variance of 'BRS3' is 0.0, metrics set to NaN
Now learning: FPR2:  53%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                                                                                                             | 222/415 [07:48<06:20,  1.97s/it]/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/liana/method/sp/_misty/_Misty.py:318: RuntimeWarning: invalid value encountered in divide
Now learning: SIGLEC9:  55%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                                                       | 229/415 [08:03<06:52,  2.22s/it]/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/liana/method/sp/_misty/_Misty.py:318: RuntimeWarning: invalid value encountered in divide
Now learning: XCR1:  55%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                                                        | 230/415 [08:05<06:39,  2.16s/it]Variance of 'XCR1' is 0.0, metrics set to NaN
Now learning: ALK:  56%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                                                     | 234/415 [08:12<06:05,  2.02s/it]/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/liana/method/sp/_misty/_Misty.py:318: RuntimeWarning: invalid value encountered in divide

In [43]:
fig = (
    li.pl.interactions(misty, view='extra', return_fig=True, figure_size=(6, 5), top_n=25, key=abs) +
    p9.scale_fill_gradient2(low="blue", mid="white", high="red", midpoint=0) +
    p9.labs(y='Receptor', x='Ligand')
)

# Display the figure
print(fig)

# Save the figure to a file
fig.save("figures/niche2_misty_ligand_receptors_interactions.png", dpi=300)

<ggplot: (600 x 500)>

/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/plotnine/ggplot.py:615: PlotnineWarning: Saving 6 x 5 in image.
/Users/annamaguza/Library/Application Support/hatch/env/virtual/single-cell-project/0fJ3OPid/single_cell_project/lib/python3.11/site-packages/plotnine/ggplot.py:616: PlotnineWarning: Filename: /Users/annamaguza/Desktop/Repos/Fetal_stem_cells_analysis/6_cci_on_imputed_spatial/figures/niche2_misty_ligand_receptors_interactions.png